stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw.csv
    outs:
      - data/x_train.csv
      - data/x_test.csv
      - data/y_train.csv
      - data/y_test.csv
      - models/scaler.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/x_train.csv
      - data/y_train.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
      - data/x_test.csv
      - data/y_test.csv
    metrics:
      - metrics.json